[workspace]
members = ["astro-math", "astro-math-py"]
resolver = "2"

[workspace.package]
version = "0.2.1"
authors = ["@gaker"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gaker/astro-math"

[workspace.dependencies]
chrono = "0.4"
thiserror = "1.0"