name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --all

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test-linux
    if: success()

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libc++-dev libc++abi-dev libusb-1.0-0-dev

      - name: Cache cargo + tarpaulin
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tarpaulin

      - name: Install Tarpaulin (if missing)
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          fi

      - name: Run code coverage
        run: cargo tarpaulin --ignore-tests --out Xml --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cobertura.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
