name: Rust CI

on:
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --all

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test-linux
    if: success()

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libc++-dev libc++abi-dev libusb-1.0-0-dev python3-dev

      - name: Cache cargo + tarpaulin
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tarpaulin

      - name: Install Tarpaulin (if missing)
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          fi

      - name: Run code coverage
        run: |
          # Run tarpaulin only on the Rust astro-math library (exclude Python bindings)
          cd astro-math
          cargo tarpaulin --ignore-tests --out Xml --verbose

      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main'  # Only upload coverage from main branch
        uses: codecov/codecov-action@v4
        with:
          files: ./astro-math/cobertura.xml
          flags: rust
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-python:
    name: Python Bindings Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov numpy

      - name: Install maturin
        run: pip install maturin
        
      - name: Build and install package
        run: |
          cd astro-math-py
          maturin build --release --out dist
          
      - name: Install built wheel
        run: |
          pip install astro-math-py/dist/*.whl

      - name: Run Python tests
        run: |
          cd astro-math-py
          python -m pytest tests/ -v --cov=astro_math --cov-report=xml

      - name: Upload Python coverage
        if: matrix.python-version == '3.11' && github.ref == 'refs/heads/main'  # Only from main
        uses: codecov/codecov-action@v4
        with:
          files: ./astro-math-py/coverage.xml
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
